# Generated by Django 3.1.2 on 2025-06-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers_payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerpayments',
            old_name='trainer',
            new_name='user',
        ),
    ]
