# Generated by Django 3.1.2 on 2025-06-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('payments', '0002_auto_20250630_0245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerPayments',
            new_name='Payments',
        ),
    ]
