# Generated by Django 3.1.2 on 2025-05-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('reg_date', models.DateField()),
                ('reg_upto', models.DateField()),
                ('sub_type', models.CharField(max_length=100)),
                ('sub_period', models.PositiveIntegerField()),
                ('fees_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees_status', models.CharField(max_length=10)),
                ('allotted_members', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
