# Generated by Django 3.1.2 on 2025-05-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='allotted_members',
        ),
    ]
