# Generated by Django 3.1.2 on 2025-05-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_auto_20250530_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceForm',
        ),
    ]
